### ISSUE TITLE
Question about SchumannGrotzbach surface stress model

### ISSUE THREAD

**Issue by RTibo** [NREL/SOWFA-6#12]
Hi!

First of all, even though I'm a fairly new user of Openfoam, let me say that your work is incredible.

If you give me the permission, I'm really interested to use some of your work, mostly the boundary condition model.

Speaking about the boundary condition model, the one I expected to use the most will be the SchumannGrotzbach boundary model. However, something in the code caught my attention.

I'm probably missing something out, but I hope you'll help me with this one.

I've seen in the literature that with beta=1.0 from Thomas & Williams (1999) 
![formulation](https://user-images.githubusercontent.com/64756528/80961195-cb3a2e80-8de0-11ea-92ca-709cb42dbd94.png), we have the Schumann-Grotzbach formulation

![formulation2](https://user-images.githubusercontent.com/64756528/80961370-33891000-8de1-11ea-88b2-95cd01a1167e.png).

I've noticed that in the code, for instance at line 346 (occur at line 349, 360 & 362 also) in file SchumannGrotzbachFvPatchField.C, that a square root to uStar is used. From the formulation I presented above, I wondering why is not uStar^2 instead of sqr(uStar). I've been looking in the code and didn't find anything related that would involve to use sqr(uStar).

In the meantime, I've another question. Do I need to compile the "planarAveraging" & "temporalAvering" function in /src/functionObjects/field/ in order to make the SchumannGrotzbach boundary model work?

Thank for answering and helping me.

Best Regards,

René Thibault

**Comment by rthedin** [comment]
If you pay close attention, it is doing `sqr(uStart)`, and not `sqrt(uStar)`. What `sqr` does is take the square of that quantity, being mindful of its type.

Regarding the compilation of those functions, I do not think you need them for the boundary condition to work. I think you would only need them if you are specifying some statistics to be saved.

**Comment by RTibo** [comment]
Oh! Your right...My bad! I don't know why I didn't noticed this detail!

So, basically, If I want yo use it, to the best of your knowledge about SOWFA-6, I don't need to compile anything else? This is just to make sure that when I'll try to compile the boundary model and if an error popup, it will not related to this. So, I'll be able to search for the problem somewhere else.

Again, thank you very much! Stay safe!

Best Regards,

**Comment by ewquon** [comment]
The surface stress BC does not depend on the `planarAveraging` and `temporalAveraging` function objects. It would be good idea to compile all of the SOWFA libraries using `./Allwmake` so that all the functionality is available, though.
