### ISSUE TITLE
vtkStructured Writer Scrambling Data

### ISSUE THREAD

**Issue by mchurchf** [NREL/SOWFA-6#30]
The vtkStructured writer does not write the field data in the correct order.  Although the points to be sampled are ordered the correct way, the actual writing happens based on processor decomposition.  It seems that once the data is sent to the master processor, it should be resorted.

**Comment by ewquon** [comment]
Some clues on sorting output from: https://github.com/OpenFOAM/OpenFOAM-6/blob/master/src/sampling/sampledSet/points/points.C

**Comment by ewquon** [comment]
The `unordered` path can result in missing sampled points; `ordered` gives all requested points, in the right order.

**Comment by mchurchf** [comment]
This problem has been fixed.
