### ISSUE TITLE
how to get precursor case of ABLterrian case

### ISSUE THREAD

**Issue by PheiGao** [NREL/SOWFA-6#40]
Hi rthedin

when I prepare to run the case 'tut.ABLterrain' in SOWFA-6/exampleCases, I find it need a precursor named '~/OpenFOAM/rthedin-6/run/precursor/neutral.W.5at80.5dTInv.0p05z'. so, could you please share this precursor case or give me some information about how to creat a precursr case. Thanks a lot.

**Comment by rthedin** [comment]
You do not _have_ to have a precursor for a terrain simulation. The options are commented out in the tutorial script:
https://github.com/NREL/SOWFA-6/blob/481fa37b493f51b3b5471c037c3ce46e72d79839/exampleCases/tut.ABLterrain/1_preprocess#L24

But, if you do choose precursor, you have to give a `precursorDir`. You can execute one yourself using the [precursor tutorial](https://github.com/NREL/SOWFA-6/tree/dev/exampleCases/tut.ABLflatTerrain.precursor). I recommend executing the precursor with the same domain limits and resolution as the intended complex terrain case.

You can initialize the internal domain with tables by using `setFieldsABL`, or, for testing purposes, `none`.

Hope it helps.

**Comment by rthedin** [comment]
I'm closing this. Feel free to post follow-up questions and/or re-open.
