### ISSUE TITLE
superDeliciousVanilla doesn't compile without OpenFAST

### ISSUE THREAD

**Issue by mak-10** [NREL/SOWFA-6#55]
The combined solver requires OpenFAST to compile, which was not the case for previous commits of SOFWA-6.  
If OpenFAST is not compiled, we get the following error.

"/home/mehtabkhan/OpenFOAM/SOWFA-6/src/turbineModels/turbineModelsOpenFAST/lnInclude/horizontalAxisWindTurbinesALMOpenFAST.H:69:10: fatal error: OpenFAST.H: No such file or directory"
Also, the standard turbine models are not available anymore; only ALMOpenFAST is possible with the latest SOWFA-6 commit.

**Comment by rthedin** [comment]
Hi Mehtab, that's right. It's by design. Now SOWFA has a single solver that requires OpenFAST.
