### ISSUE TITLE
Running tut.ABLflatTerrain.precursor arithmetic and running 2_solve reported an error

### ISSUE THREAD

**Issue by fengbao520** [NREL/SOWFA-6#63]
Running tut.ABLflatTerrain.precursor arithmetic and running 2_solve reported an error.The terminal displays as shown

./2_solve: line 3: OpenFOAM-6-dev-central: command not found
Job killed (1)
./2_solve: line 15: scancel: command not found
Case not reconstructed and first time of boundaryData not fixed. Check if endTime dir exists.
ls: cannot access 'postProcessing/boundaryData/north': No such file or directory
ls: cannot access 'postProcessing/boundaryData/south': No such file or directory
ls: cannot access 'postProcessing/boundaryData/east': No such file or directory
ls: cannot access 'postProcessing/boundaryData/west': No such file or directory

The log. 2. decomposePar file displays as follows：
--> FOAM Warning : 
    From function void* Foam::dlOpen(const Foam::fileName&, bool)
    in file POSIX.C at line 1234
    dlopen error : libSOWFAincompressibleTurbulenceModels.so: cannot open shared object file: No such file or directory
--> FOAM Warning : 
    From function bool Foam::dlLibraryTable::open(const Foam::fileName&, bool)
    in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 105
    could not load "libSOWFAincompressibleTurbulenceModels.so"

I would greatly appreciate it if you could tell me where the mistake was or how to adjust it.
Thanks.

**Comment by rthedin** [comment]
There are several errors that are all printed right there. 

> ./2_solve: line 3: OpenFOAM-6-dev-central: command not found

You don't have your environment set.

> Job killed (1)

See what job killed (1) means in the script. Did you run the first script before running the second?

> ./2_solve: line 15: scancel: command not found

Are you using SLURM?

> Case not reconstructed and first time of boundaryData not fixed. Check if endTime dir exists.

That was printed later on. The solver didn't run so this error was printed. Open the script to see where this is coming from.

>  libSOWFAincompressibleTurbulenceModels.so: cannot open shared object file: No such file or directory

Did you install SOWFA correctly?

**Comment by fengbao520** [comment]
Thanks for your reply.
Yes, I run the first script before running the second.The first script is running successfully,but the second script runs with an error.

**Comment by fengbao520** [comment]
> 有几个错误都打印在那里。
> 
> > ./2_solve：第 3 行：OpenFOAM-6-dev-central：找不到命令
> 
> 您没有设置环境。
> 
> > 约伯被杀 （1）
> 
> 看看脚本中被杀死的作业 （1） 是什么意思。您是否在运行第二个脚本之前运行了第一个脚本？
> 
> > ./2_solve：第 15 行：取消：找不到命令
> 
> 您是否正在使用 SLURM？
> 
> > 案例未重建，边界数据首次未修复。检查是否存在结束时间目录。
> 
> 那是后来印刷的。求解器未运行，因此打印了此错误。打开脚本以查看其来源。
> 
> > libSOWFAincompressibleTurbulenceModels.so：无法打开共享对象文件：没有此类文件或目录
> 
> 是否正确安装了 SOWFA？

Can you tell me how to determine if sowfa-6 is installed correctly?I have not yet resolved the above issue. I may need your help.Thanks.

**Comment by fengbao520** [comment]
> 编译应该已经成功了。您应该不会在呼叫的日志中看到任何错误消息。另一种方法是通过简单地调用或尝试来查看求解器是否可用。如果是，您可能还需要密切注意打印的消息，以确保打印没有错误或警告。`make``which superDeliciousVanilla`
> 
> 如果您只是调用脚本而不逐行浏览它并了解它在做什么，那么您将很难跟踪错误，因为您甚至不知道它在哪里崩溃。我建议获取一个交互式节点（如果使用 HPC）并逐行浏览它。第一行表示尚未设置环境。[此处](https://github.com/NREL/SOWFA-6/blob/dev/environmentScripts/OF-6-env-gcc-central)提供了一个示例。

**Comment by fengbao520** [comment]
> 编译应该已经成功了。您应该不会在呼叫的日志中看到任何错误消息。另一种方法是通过简单地调用或尝试来查看求解器是否可用。如果是，您可能还需要密切注意打印的消息，以确保打印没有错误或警告。`make``which superDeliciousVanilla`
> 
> 如果您只是调用脚本而不逐行浏览它并了解它在做什么，那么您将很难跟踪错误，因为您甚至不知道它在哪里崩溃。我建议获取一个交互式节点（如果使用 HPC）并逐行浏览它。第一行表示尚未设置环境。[此处](https://github.com/NREL/SOWFA-6/blob/dev/environmentScripts/OF-6-env-gcc-central)提供了一个示例。

Thanks for your reply.I think I just didn't set up the environment, but I'm still having problems with the setup process, I'll try again. Thanks again for your reply.
