### ISSUE TITLE
Has anyone successfully compiled this in Ubuntu?

### ISSUE THREAD

**Issue by CallumG-Ed** [NREL/SOWFA-6#7]
I have been trying to compile this SOWFA-6 version in Ubuntu 18.04 using the attached [bash_profile](https://github.com/NREL/SOWFA-6/files/4355942/bash_profile.txt).
The ./Allwmake doesn't seem to build the libraries - heres the [log](https://github.com/NREL/SOWFA-6/files/4355936/log_make.txt).

**Comment by RTibo** [comment]
Did you fin a solution to your issue? The Ubuntu version I use is older then yours though (Ubuntu 16.04.5 LTS), but still got the same issue.

**Comment by CallumG-Ed** [comment]
No unfortunately not. I didn’t put much effort into finding a solution I decided to revert to the original version. I would still be interested in a solution if anyone finds one!

**Comment by rthedin** [comment]
Has OpenFOAM-6 been compiled successfully? I took a look at your log file and the first error is that it can't find the `finiteVolume` and `meshTools` libraries. Most of the subsequent errors are rooted in the same issue. Check your OpenFOAM compilation and see if your libraries are in `$FOAM_LIBBIN`.

**Comment by RTibo** [comment]
Thank for replying. 

Since I use the OpenFoam v1906 distribution, do you think that could still work? I'll give it a try this weekend and see again what type of error I got.

**Comment by CallumG-Ed** [comment]
> Has OpenFOAM-6 been compiled successfully? I took a look at your log file and the first error is that it can't find the `finiteVolume` and `meshTools` libraries. Most of the subsequent errors are rooted in the same issue. Check your OpenFOAM compilation and see if your libraries are in `$FOAM_LIBBIN`.

Yes OpenFOAM is compiled and working so I'm assuming its some kind of permissions issue. But I am not too confident with this kind of thing. I have ran simulations in OpenFOAM-6 successfuly so assuming it is working fine.

**Comment by RTibo** [comment]
If I remember well, I think it was a permissions issue also. Glad that you found a workaround. I'll try to find a solution this weekend....

**Comment by rthedin** [comment]
@RTibo I'm not sure if it will work on this version on OpenFOAM you mentioned. My experience is that for the most part, if it is a major release, lots of small details will need to be corrected in SOWFA.

Regarding the actual compilation, it is unlikely that is a permission issue, judging by the log file you attached. You are trying to write in `$FOAM_INST_DIR/$USER-$OPENFOAM_VERSION/SOWFA-6` which you should have write permissions. My guess is that you had something wrong with these paths. I would go and check if they exist, and if the right files are inside the directories they should be in. You can also check some of these paths being set in the `$FOAM_ETC/config.sh/settings` file. Good luck!
