### ISSUE TITLE
Angled wind- 'sources' file for ALM

### ISSUE THREAD

**Issue by nsdangi** [NREL/SOWFA-6#71]
Hello, 

I wanted to clarify about the use of SOWFA6 ABL precursor file in the ALM turbine simulations, when the wind is not from West (270deg); but, for example, SouthWest (225deg). 

1. Could you clarify if any care should be taken for such a case, for the 'sources' file preparation OR are the conventional sourceTableMomentumX, Y, Z entries enough? 

2. And, should one save boundary data of the precursor at both, west and south boundaries ?

Thank you very much for the tool !

**Comment by rthedin** [comment]
No additional care is needed for the sources file. The different components of `sourceTableMomentum*` handle that.

Regarding the boundary data, yes, you do want to save boundary data at every inflow boundary of your ALM simulation. So in your case you want to save both west and south.

**Comment by nsdangi** [comment]
Ok! Thanks a lot for clarifying, @rthedin Regis . May I ask you a follow up question? 
What should these values be for  `T` and `U`  `boundaryField` patches? I am unable to find the definitions or code for it.. 
```
south
            {
                type            timeVaryingMappedInletOutlet;

                valueFraction   uniform 0; #What value? In my case of south-west or general angled wind 

                refValue        uniform 0; 

                value           uniform 0; #How to have values taken from the `sources` file? 
            }
```

For example, I am looking at this [changeDictionaryDict](https://github.com/NREL/SOWFA-6/blob/dev/exampleCases/tut.ABLflatTerrain.run/system/changeDictionaryDict.TVMIO). 

Looking forward to hear back from you, thanks !

**Comment by rthedin** [comment]
No need to change any of that. The `timeVaryingMappedInletOutlet` boundary condition follows the `timeVaryingMappedFixedValue`, which expects the boundary data to be inside `constant/boundaryData` (see [here](https://www.openfoam.com/documentation/guides/latest/api/classFoam_1_1timeVaryingMappedFixedValueFvPatchField.html): "Supplied data should be specified in `constant/boundaryData/<patchname>/`").

**Comment by nsdangi** [comment]
Alright, clear! thank you Regis,
