### ISSUE TITLE
Using fvOptions in the actuator line implementation

### ISSUE THREAD

**Issue by hcOnel** [NREL/SOWFA-6#75]
This is more of a technical question, but I'm curious why the actuator line model was implemented as a new solver instead of utilizing the fvOptions feature. Was this decision influenced by version-related issues? Or does the fvOptions implementation have computational penalties that make adding it to the solver more efficient?

**Comment by mchurchf** [comment]
The actuator line was implemented long ago using an older version of OpenFOAM before the fvOptions functionality was part of OpenFOAM.  Although it would be nice to incorporate the actuator line into fvOptions format, we currently lack the time to do that, and the current actuator line library that is linked to superDeliciousVanilla works well, so we keep it for now.
